### ISSUE TITLE
[Bug]: Announcement to all users doesn't work

### ISSUE THREAD

**Issue by jevail** [rupadana/filament-announce#13]
### What happened?

I cannot add an announcement for all users

### How to reproduce the bug

Create a new announcement, check 'all users'

### Package Version

3.1.5

### PHP Version

8.2

### Laravel Version

10.3.3

### Which operating systems does with happen with?

macOS, Linux

### Notes

migration does not contain an 'all' field

**Comment by rupadana** [comment]
Hey @jevail, sorry for having that problem. yesterday someone create some PR & its been merged, but im missing some parts like migration.

its already revert to version 3.1.4, please update your package to version 3.1.7.

You can tell me here if you still seen that bugs

**Comment by Rizayev** [comment]
@rupadana Hi, check CreateAnnouncement  dd($record->users); check user_id

**Comment by Rizayev** [comment]
Add new field, make migration
 `$table->boolean('all')->default(false);`
make it fillable
