### ISSUE TITLE
Add sort to menu in config

### ISSUE THREAD

**Issue by darren-glanville** [rupadana/filament-announce#15]
### What happened?

I would like to be able to add navigation_sort to the config so I can change the position within the menu.

Is this something that can be added

### How to reproduce the bug

n/a

### Package Version

3.1.7

### PHP Version

8.3

### Laravel Version

10

**Comment by rupadana** [comment]
I don't think this is a bug, just needs some changes to be added soon.

**Comment by rupadana** [comment]
this already available at our last release, please update the package
