### ISSUE TITLE
How can I customize AnnouncementResource without editing vendor files?

### ISSUE THREAD

**Issue by CharlieEtienne** [rupadana/filament-announce#17]
### What happened?

I would like to change multiple things, like translate labels and customize the user query.

### How to reproduce the bug

Install the plugin

### Package Version

3.1.7

### PHP Version

8.3

### Laravel Version

10.43.0

**Comment by rupadana** [comment]
currently is not possible to do it, but we need update it to be possible

**Comment by CharlieEtienne** [comment]
I proposed a PR for that: https://github.com/rupadana/filament-announce/pull/19

**Comment by rupadana** [comment]
Thank you for your contribution ☺️, PR is already merged & released.
