### ISSUE TITLE
Laravel 11.x Compatibility

### ISSUE THREAD

**Issue by theanadimukt** [rupadana/filament-announce#18]
### What happened?

Package dependency illuminate/contracts should be compatible with new Laravel release

### How to reproduce the bug

Try to install package with Laravel 11

### Package Version

3.1.7

### PHP Version

8.2.0

### Laravel Version

11.0.0

### Which operating systems does with happen with?

Linux

**Comment by rupadana** [comment]
Thank you for your advice, will be updated ASAP. But, I'am happy if you can contribute into it by forking the repository and make some PR

**Comment by rupadana** [comment]
Please update to version 3.2

**Comment by theanadimukt** [comment]
Sorry I couldn't find time to update, Happy to see you did it. Thank you ❤️
